### ISSUE TITLE
Text out of background

### ISSUE THREAD

**Issue by legabi** [bdebon/choiceof.dev#172]
The text on [this page](https://choiceof.dev/question/music-or-stackoverflow/) is out of backgroud, it is a joke or it's a bug ?

![image](https://user-images.githubusercontent.com/69119038/205756709-24a0d96a-5f94-4bde-b212-becb387f7039.png)

**Comment by legabi** [comment]
if it's a bug, I can try to solve it

**Comment by andronedev** [comment]
It's a joke
