### ISSUE TITLE
Pluging google analytic to track page changes and any useful information

### ISSUE THREAD

**Issue by bdebon** [bdebon/choiceof.dev#33]
I plugged Google Analytic but I did just the bare minimum.
For now it just track the number of visitors.
Which could be nice would be to track also then number of page viewed, in which answer the user has clicked for each pages etc...
Anything that could be pertinent and gives us some precious data that some of you will be able to analyse later on.

**Comment by Barbapapazes** [comment]
Google analytics is now illegal in French.

https://www.forbes.com/sites/emmawoollacott/2022/02/10/french-regulator-rules-google-analytics-illegal/

Here 2 alternatives:
- Plausible
- Matomo

**Comment by babache** [comment]
Matono !

**Comment by Pab450** [comment]
Matomo +1

**Comment by CyrilNb** [comment]
What about SimpleAnalytics or Fathom? Why Matomo over the others? (just asking I'm curious)

**Comment by bdebon** [comment]
done https://github.com/bdebon/choiceof.dev/pull/57
